### ISSUE TITLE
Upload not possible any more due to java exception

### ISSUE THREAD

**Issue by alexquast** [mwaylabs/relution-jenkins-plugin#3] opened 2015-05-21 18:22 UTC
Uploading new versions fails now with Exception

```
java.util.concurrent.ExecutionException: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
    at org.apache.http.concurrent.BasicFuture.getResult(BasicFuture.java:68)
    at org.apache.http.concurrent.BasicFuture.get(BasicFuture.java:77)
    at org.jenkinsci.plugins.relution_publisher.net.RequestManager.send(RequestManager.java:126)
    at org.jenkinsci.plugins.relution_publisher.net.RequestManager.execute(RequestManager.java:210)
    at org.jenkinsci.plugins.relution_publisher.builder.ArtifactFileUploader.uploadAsset(ArtifactFileUploader.java:489)
    at org.jenkinsci.plugins.relution_publisher.builder.ArtifactFileUploader.uploadAssets(ArtifactFileUploader.java:468)
    at org.jenkinsci.plugins.relution_publisher.builder.ArtifactFileUploader.invoke(ArtifactFileUploader.java:112)
    at org.jenkinsci.plugins.relution_publisher.builder.ArtifactFileUploader.invoke(ArtifactFileUploader.java:58)
    at hudson.FilePath.act(FilePath.java:989)
    at hudson.FilePath.act(FilePath.java:967)
    at org.jenkinsci.plugins.relution_publisher.configuration.jobs.ArtifactPublisher.publish(ArtifactPublisher.java:128)
    at org.jenkinsci.plugins.relution_publisher.configuration.jobs.ArtifactPublisher.perform(ArtifactPublisher.java:92)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
    at hudson.model.Build$BuildExecution.post2(Build.java:183)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
    at hudson.model.Run.execute(Run.java:1775)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Could not generate DH keypair
    at org.apache.http.nio.reactor.ssl.SSLIOSession.convert(SSLIOSession.java:215)
    at org.apache.http.nio.reactor.ssl.SSLIOSession.doUnwrap(SSLIOSession.java:230)
    at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:263)
    at org.apache.http.nio.reactor.ssl.SSLIOSession.isAppInputReady(SSLIOSession.java:391)
    at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:119)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:159)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:338)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:316)
    at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:277)
    at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
    at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:584)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Could not generate DH keypair
    at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:136)
    at sun.security.ssl.ClientHandshaker.serverKeyExchange(ClientHandshaker.java:688)
    at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:261)
    at sun.security.ssl.Handshaker.processLoop(Handshaker.java:901)
    at sun.security.ssl.Handshaker$1.run(Handshaker.java:841)
    at sun.security.ssl.Handshaker$1.run(Handshaker.java:839)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1273)
    at org.apache.http.nio.reactor.ssl.SSLIOSession.doRunTask(SSLIOSession.java:238)
    at org.apache.http.nio.reactor.ssl.SSLIOSession.doHandshake(SSLIOSession.java:276)
    ... 9 more
Caused by: java.security.InvalidAlgorithmParameterException: Prime size must be multiple of 64, and can only range from 512 to 1024 (inclusive)
    at com.sun.crypto.provider.DHKeyPairGenerator.initialize(DHKeyPairGenerator.java:120)
    at java.security.KeyPairGenerator$Delegate.initialize(KeyPairGenerator.java:658)
    at sun.security.ssl.DHCrypt.<init>(DHCrypt.java:127)
    ... 18 more
```

**Comment by mpfeiffermway** [comment] 2015-05-21 19:33
This is most likely caused by the Java version installed on your Jenkins server. It looks like the Java version on your Jenkins server is not compatible with the prime size of the TLS/SSL connection of the Relution server (>1,024 bits).

See these links for more information:
- http://stackoverflow.com/questions/6851461/java-why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception
- https://blog.bartlweb.net/2014/12/ssl-verbindungen-mit-mehr-als-1024-bit-werden-unter-java-1-6-abgelehnt/

I'll have to verify tomorrow, but afaik our Jenkins server has been running on Java 1.8 for some time now.

**Comment by mpfeiffermway** [comment] 2015-06-11 11:37
This is fixed by installing a Java version that supports TLS/SSL keys with more than 1,024 bit.

You can verify whether your Java installation supports "unlimited" encryption strength by using this snippet: https://gist.github.com/jehrhardt/5167854.

If your Java installation is cryptographically limited you need to install the Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files for…
- [Java 1.7](http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html)
- [Java 1.8](http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html)

Alternatively you can use OpenJDK, which has been Java's reference implementation since Java 1.7. See http://derjan.io/blog/2013/03/15/nevermind-jce-unlimited-strength-use-openjdk/.

**Closed as completed by mpfeiffermway** 2015-06-11 11:37 UTC
